# Generated by Django 2.2.5 on 2019-09-19 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('description', models.TextField(max_length=3000, verbose_name='Description')),
                ('category', models.CharField(choices=[('other', 'Other'), ('bras', 'Bras'), ('panties', 'Panties'), ('swimwear', 'Swim'), ('sleepwear', 'Sleep')], default='other', max_length=20, verbose_name='Category')),
                ('remainder', models.IntegerField(verbose_name='Remainder')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Price')),
            ],
        ),
    ]
